config/routes.rb
Rails.application.routes.draw do
	get 'home/about'
	devise_for :users
	resources :books,only: [:new, :create, :index, :show, :destroy, :edit, :update] do
		resource :favorites, only: [:create, :destroy]
		resources :book_comments,only: [:create, :destroy]
	end
	post "relationships/:id" => "relationships#create", as: "follow"
	delete "relationships/:id" => "relationships#destroy", as: "unfollow"
	root 'home#top'
	get 'follower_users/:id' => "users#follower_users", as: "followers"
	get 'follow/:id' => "users#follow", as: "follows"
  resources :users,only: [:show,:index,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'followed_id'
  has_many :follows, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :follower, source: :follower
  attachment :profile_image, destroy: false
# ユーザーをフォローする
  def follow(other_user)
     self.follows.create!(followed_id: other_user)
  end

  def unfollow(other_user)
     self.follows.find_by(followed_id: other_user).destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
	    comment.book_id = book.id
	    comment.save
	    redirect_to book_path(book)
	end

	def destroy
		@book_comment = BookComment.find(params[:book_id])
		@book_comment.destroy
		redirect_to book_path(params[:book_id])
	end

	 private
	  def book_comment_params
	    params.require(:book_comment).permit(:comment)
	  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!, only: [:update, :edit, :show, :index]
  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
	book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
	end

	def destroy
	book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
	end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def FollowUsers
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    if current_user.follow(params[:id])
      flash[:success] = 'ユーザーをフォローしました'
      redirect_back(fallback_location: users_path)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: users_path)
    end
  end

  def destroy
    if current_user.unfollow(params[:id])
      flash[:success] = 'ユーザーのフォローを解除しました'
     redirect_back(fallback_location: users_path)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
     redirect_back(fallback_location: users_path)
    end
  end

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :show, :index]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follower_users
    @user = User.find(params[:id])
    @users = User.all
    @book = Book.new
  end

  def follow
    @user = User.find(params[:id])
    @users = User.all
    @book = Book.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
<% if f.object.errors.any? %>
  <div class="alert alert-warning">
    <h3><%= pluralize(f.object.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    </div>
    <% end %>
  <% end %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
				<!-- <いいね> -->
						<td>
							<% if book.favorited_by?(current_user) %>
							  <%= link_to book_favorites_path(book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= book.favorites.count %>
							  <% end %>
							<% else %>
							  <%= link_to book_favorites_path(book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= book.favorites.count %>
							  <% end %>
							<% end %>
						</td>
						<!-- <いいね終了> -->

						<!-- <コメント数> -->
						<td>コメント数：<%= book.book_comments.count %></td>
						<!-- <コメント数終了> -->
					</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @book.user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
					<tr>
						<td>
							<%= link_to user_path(@book.user) do %>
								<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
							<% end %>
						</td>
						<td><%= link_to @book.title, book_path(@book) %></td>
						<td><%= @book.body %></td>

						<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
						<% end %>

						<!-- <いいね> -->
						<td>
							<% if @book.favorited_by?(current_user) %>
							  <%= link_to book_favorites_path(@book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= @book.favorites.count %>
							  <% end %>
							<% else %>
							  <%= link_to book_favorites_path(@book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= @book.favorites.count %>
							  <% end %>
							<% end %>
						</td>
						<!-- <いいね終了> -->

						<!-- <コメント数> -->
						<td>コメント数：<%= @book.book_comments.count %></td>
						<!-- <コメント数終了> -->
					</tr>
				</table>
				<!-- <コメント本文> -->
				<ol>
			  <% @book.book_comments.each do |book_comment| %>
			    <li class="comment">
			      <div class="comment-body bb">
			        <div class="comment-avatar">
			          <div class="avatar">
			            <span><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %></span>
			            <span><%= book_comment.user.name %></span>
			            <span><%= book_comment.comment %></span>
			            <span><% if book_comment.user == current_user %>
			          <%= link_to "Destroy", book_book_comment_path(book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
			      		<% end %>
			      		</span>
			          </div>
			        </div>
			    </div>
			          <!-- <コメント削除> -->
			      		<!-- <コメント削除> -->
			    </li>
			  <% end %>
			</ol>
			<!-- <コメント本文終了> -->

			<!-- <入力フォーム> -->
			<%= form_for [@book, @book_comment] do |f| %>
			      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			  <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
			<!-- <入力フォーム終了> -->

		</div>
	</div>
</div>

app/views/follows/FollowUsers.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>Follow Users</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
							<td><%= user.name %></td>
							<td>フォロー数:<%= user.followings.count %></td>
							<td>フォロワー数:<%= user.followers.count %></td>
							<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
						<% end %>
						</tr>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>Follower Users</h2>
				<!--users一覧 -->
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
							<td><%= user.name %></td>
							<td>フォロー数:<%= user.followings.count %></td>
							<td>フォロワー数:<%= user.followers.count %></td>
							<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
							<% end %>
						</tr>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= link_to user.followings.count, follows_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followers.count, followers_path(user) %></th>
	</tr>
</table>

<div class="row">
	<% if user == current_user %>
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% else %>
	<% unless user == current_user %>
	  <% if current_user.following?(user) %>
	    <%= link_to 'フォロー外す', unfollow_path(user.id),  method: :delete, class: "col-xs-12 btn btn-default " %>
	  <% else %>
	    <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "col-xs-12 btn btn-default " %>
	  <% end %>
	<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
<% if f.object.errors.any? %>
  <div class="alert alert-warning">
    <h3><%= pluralize(f.object.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/follow.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-9">

			<h2>Follow Users</h2>
				<!--users一覧 -->
			<% if @user.followings.count >= 1%>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @user.followings.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
							<td><%= user.name %></td>
							<td>フォロー数:<%= user.followings.count %></td>
							<td>フォロワー数:<%= user.followers.count %></td>
							<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
							<% end %>
						</tr>
					</tbody>
				</table>
			<% else %>
				<p>ユーザーは存在しません。</p>
			<% end %>
		</div>
	</div>
</div>

app/views/users/follower_users.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-9">

			<h2>Follower Users</h2>
				<!--users一覧 -->
			<% if @user.followers.count >= 1%>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @user.followers.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
							<td><%= user.name %></td>
							<td>フォロー数:<%= user.followings.count %></td>
							<td>フォロワー数:<%= user.followers.count %></td>
							<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
							<% end %>
						</tr>
					</tbody>
				</table>
			<% else %>
				<p>ユーザーは存在しません。</p>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

	<div class="col-xs-9">
		<h2>Users</h2>
	<!--users一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th></th>
				<th></th>
				<th></th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>




				<td>フォロー数:<%= user.followings.count %></td>
				<td>フォロワー数:<%= user.followers.count %></td>
				<td>
					<% unless user == current_user %>
					  <% if current_user.following?(user) %>
					    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete %>
					  <% else %>
					    <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
					  <% end %>
					<% end %>
					</td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			<% end %>

			</tr>
		</tbody>
	</table>
	<!--users一覧 -->
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--books一覧 -->
		</div>
	</div>
</div>
<% current_user.followings.each do |u| %>
<p><%= u.id %></p>
<% end %>